### ISSUE TITLE
Collaboration and Github

### ISSUE THREAD

**Issue by jalynkyrgyz** [CoDemIT2021/Collaboration-with-Step-by-Step#2]
- [x]  Укажите задачу
GitHub как средство общения для команды.  Данный челендж про роль GitHub во внутренних процессах небольшой команды.
- [x]  Укажите цель
Для создания веб-сайта , разработатки мобильного или веб-приложение или выполнения заданий по спринтам со своими товарищами по команде. 
Суть-это простой способ поделиться фрагментами кода и вставками с другими. 
GitHub используется, когда вам нужно поделиться образцом кода или техники со своими коллегами или друзьями. Вы можете поделиться одним файлом, статьями, полными приложениями или исходным кодом.
- [x]  Укажите путь

**Comment by AzamatZhamankulov** [comment]
all done
