### ISSUE TITLE
Creativity and Critical thinking (Youtube/ Instagram)

### ISSUE THREAD

**Issue by jalynkyrgyz** [CoDemIT2021/Collaboration-with-Step-by-Step#3]
Youtube

- [x]  Провести встречу с другой командой для обмена опытом
- [x]  Совместный проект на тему "Что такое командная работа"
- [x]  Показать свой проект 21-августа в 21-00

Instagram

- [x]  Каждый участник команды готовит по 1-му посту в неделю (не менее 5 постов
- [x]  Тема этой недели - "**Интересные факты** *(о компаниях /технологиях /людях в IT*)"
- [x]  Длинные и полезные статьи (найденные в процессе поиска материала и не поместившиеся в Intstagram) - опубликовать в Post Blog команды для ознакомления

**Comment by ukmoldogazy** [comment]
Done!!!
